// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:0eec694c-d342-414c-b013-f4287be80b3d",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_HSNXCoZyL",
    "aws_user_pools_web_client_id": "6qb152bgmcda8o2qevdsdid2ju",
    "aws_user_files_s3_bucket": "imageuploads-mclinical-salaunch",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
